### PR TITLE
Fix TypeScript error: add missing sendUpdate argument to createLinkManager

### LINKED ISSUE #312: TypeScript error: createLinkManager called with wrong number of arguments
## Description

`src/isolated-renderer/widget-provider.tsx` calls `createLinkManager` with only 1 argument, but the function signature requires 2:

```typescript
// widget-provider.tsx line 95
useEffect(() => createLinkManager(client.store), [client.store]);
```

```typescript
// link-subscriptions.ts
export function createLinkManager(
  store: WidgetStore,
  sendUpdate: SendUpdate,  // Missing in call
): () => void {
```

## Error

```
src/isolated-renderer/widget-provider.tsx(95,19): error TS2554: Expected 2 arguments, but got 1.
```

## Fix

Pass `client.sendUpdate` as the second argument:

```typescript
useEffect(() => createLinkManager(client.store, client.sendUpdate), [client.store, client.sendUpdate]);
```

## Impact

This breaks TypeScript compilation (`npx tsc --noEmit` fails).

### PR DESCRIPTION
**Pull request by rgbkrk**
The `createLinkManager` function in `link-subscriptions.ts` requires 2 arguments, but was called with only 1 in the isolated iframe widget provider, causing a TS2554 compilation error.

This adds the missing `client.sendUpdate` argument, ensuring linked widget values are synced back to the kernel as intended.

Closes #312

_PR submitted by @rgbkrk's agent, Quill_

### CODE REVIEW

File: src/isolated-renderer/widget-provider.tsx [hunk 1]
```diff
@@ -92,7 +92,10 @@ export function IframeWidgetStoreProvider({
   }, [client]);
 
   // Set up link subscriptions (jslink/jsdlink)
-  useEffect(() => createLinkManager(client.store), [client.store]);
+  useEffect(
+    () => createLinkManager(client.store, client.sendUpdate),
+    [client.store, client.sendUpdate],
+  );
```
Comment (rgbkrk) [inline src/isolated-renderer/widget-provider.tsx:98]: Wait is this missing from nteract elements too?
